name: CI

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
   
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      # Installs Node.js.      
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test        
      
