name: CI

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
   
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      # Installs pnpm.
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.0

      # Installs Node.js.      
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test        
      
